language: node_js
node_js:
- '7'

cache:
  directories:
  - node_modules

before_install: 
  - 
    
deploy:
  provider: heroku
  api_key:
    secure: VXcOsuQNYyp5E6EFhYS3V4+oZgDGYeFad/QLQM7pKUetQJo47vIgYanzSFyVngiKWkj0XkyFWushALhlr0sgdEVpaE6+s1pNIogwt7BrTIUZksKvVVS3o3cx8TqZpA8WTEji/91+kULrXUv/o0c4kWWFljqulfdN8tUSyiPBexzb3GlWpZbZv7eCiKpSEIO8O8OsnjAECF50jutmo7bswQVIHhvuZFgD5NnsECJiQGMAVnMIzDvuNGxF+l18guyoerKCkqkGqMwtUZ9ZGcLIidFr37jjfkWswoJM3kUhm2DcujrFLVQYcs6VlH90guaELizxrmkDtWYzBG2nKKpm5ze8pUoxK9xG786haPcB/0h8QpTWIpN6B7VJTu4De1uqIa+s82gIw/HiFeLXpLsQ5mD/4E0H1PPMM3+Qjicy8hNEWwWbB1BVmgLXAhJ5+GLMKHkI8F4At6zAsqAPdA51fX0v2+4N+aJuPhhFnc5H46d7uwYjY2xKx7pdXCZbImSuo7MKR3q28i/5jfFPUbtmw9+Vz4zavStobc33moPrePRbY9BlN+5MMnJCkfINUjjM7cO4ggcqt9MO+yLrk41pRr6FTVncycIGlPuRfpzN9u9B1dPJFYjrxIe5hCiU6UZ1rfr43AmK55/5xdww06gO2r7F6GWzxxV9wXxfet7Qo/g=
  app: ufus-prod

services:
  - redis-server
